parameters:
services:
    sonata.admin.block.admin_head:
        class: Ant\AdminBundle\Block\AdminHeadBlockService
        arguments: ["sonata.admin.block.admin_head", @templating, @sonata.admin.pool]
        tags:
            - { name: sonata.block}
    form.type.tinymce:
        class: Ant\AdminBundle\Form\TinymceType
        tags:
            - { name: form.type, alias: tinymce }