#index:
#    path: /
#    controller: App\Controller\DefaultController::index

ant:
  resource: "@AntWebBundle/Resources/config/routing.yml"
  prefix:   /

agreement:
  path:  /{id}-{slug}
  defaults: { _controller: "AntWebBundle:Page:showBlank", id: "4" }

hbdom:
  prefix:   /
  resource: App\Controller\HBDOMController
  type:     annotation


ad_one:
    path: /ad_one
    defaults:
        _controller: AntWebBundle:Ad:show
        id: 1
        adTemplate:    /ant_web_bundle/ad/_ad_one.html.twig
ad_two:
    path: /ad_two
    defaults:
        _controller: AntWebBundle:Ad:show
        id: 21
        adTemplate:    /ant_web_bundle/ad/_ad_three.html.twig

technology_ad_two:
    path: /technology_ad_two
    defaults:
        _controller: AntWebBundle:Ad:listOneGroup
        id: 2
        adGroupTemplate:    /ant_web_bundle/ad/_ad_two.html.twig

technology_ad_three:
    path: /technology_ad_three
    defaults:
        _controller: AntWebBundle:Ad:listOneGroup
        id: 3
        adGroupTemplate:    /ant_web_bundle/ad/_ad_two.html.twig

technology_ad_five:
    path: /technology_ad_five
    defaults:
        _controller: AntWebBundle:Ad:listOneGroup
        id: 5
        adGroupTemplate:    /ant_web_bundle/ad/_ad_two.html.twig

technology_ad_six:
    path: /technology_ad_six
    defaults:
        _controller: AntWebBundle:Ad:listOneGroup
        id: 6
        adGroupTemplate:    /ant_web_bundle/ad/_ad_two.html.twig

services_ad_four:
    path: /services_ad_four
    defaults:
        _controller: AntWebBundle:Ad:listOneGroup
        id: 4
        adGroupTemplate:    /ant_web_bundle/services/_block.html.twig

technology_pie:
    path: /technology_pie
    defaults:
            _controller: AntWebBundle:Ad:Index

services_gallery:
    path: /services_gallery
    defaults:
        _controller: AntMediaBundle:Gallery:customView
        id: 6
        galleryTemplate: /ant_web_bundle/services/_gallery.html.twig

gregwar_captcha_routing:
    resource: "@GregwarCaptchaBundle/Resources/config/routing/routing.yml"