ant_order:
    resource: "@AntWebBundle/Resources/config/routing/orderform.yml"
    prefix:   /order


ant_news:
    resource: "@AntWebBundle/Resources/config/routing/news.yml"
    prefix:   /news


ant_admin:
    resource: "@AntAdminBundle/Resources/config/routing.yml"
    prefix:   /


ad:
    pattern:  /
    defaults: { _controller: "AntWebBundle:Ad:index" }


admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

_imagine:
    resource: .
    type:     imagine

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile


gallery:
    resource: '@AntMediaBundle/Resources/config/routing/gallery.yml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

#gregwar_captcha_routing:
#    resource: "@GregwarCaptchaBundle/Resources/config/routing/routing.yml"
#    prefix: /_gcb
